package vimebu

import (
	"github.com/VictoriaMetrics/metrics"
)

// GetOrCreateHistogram calls [metrics.GetOrCreateHistogram] using the Builder's accumulated string as argument.
func (b *Builder) GetOrCreateHistogram() *metrics.Histogram {
	return metrics.GetOrCreateHistogram(b.String())
}

// GetOrCreateHistogramInSet calls [metrics.Set.GetOrCreateHistogram] using the Builder's accumulated string as argument.
func (b *Builder) GetOrCreateHistogramInSet(set *metrics.Set) *metrics.Histogram {
	return set.GetOrCreateHistogram(b.String())
}

// NewHistogram calls [metrics.NewHistogram] using the Builder's accumulated string as argument.
func (b *Builder) NewHistogram() *metrics.Histogram {
	return metrics.NewHistogram(b.String())
}

// NewHistogramInSet calls [metrics.Set.NewHistogram] using the Builder's accumulated string as argument.
func (b *Builder) NewHistogramInSet(set *metrics.Set) *metrics.Histogram {
	return set.NewHistogram(b.String())
}

// Methods with validation.

// ValidateGetOrCreateHistogram calls [metrics.GetOrCreateHistogram] using the Builder's accumulated string as argument.
//
// It returns an error if the provided metric is invalid, as per the [metrics.ValidateMetric] function.
//
// This is useful when you want to avoid the runtime panic generated by VM when a metric is invalid.
func (b *Builder) ValidateGetOrCreateHistogram() (*metrics.Histogram, error) {
	return b.ValidateGetOrCreateHistogramInSet(defaultSet)
}

// ValidateGetOrCreateHistogramInSet calls [metrics.Set.GetOrCreateHistogram] using the Builder's accumulated string as argument.
//
// It returns an error if the provided metric is invalid, as per the [metrics.ValidateMetric] function.
//
// This is useful when you want to avoid the runtime panic generated by VM when a metric is invalid.
func (b *Builder) ValidateGetOrCreateHistogramInSet(set *metrics.Set) (*metrics.Histogram, error) {
	name := b.String()
	if err := validateMetric(name); err != nil {
		return nil, err
	}
	return set.GetOrCreateHistogram(name), nil
}

// ValidateNewHistogram calls [metrics.NewHistogram] using the Builder's accumulated string as argument.
//
// It returns an error if the provided metric is invalid, as per the [metrics.ValidateMetric] function.
//
// This is useful when you want to avoid the runtime panic generated by VM when a metric is invalid.
func (b *Builder) ValidateNewHistogram() (*metrics.Histogram, error) {
	return b.ValidateNewHistogramInSet(defaultSet)
}

// ValidateNewHistogramInSet calls [metrics.Set.NewHistogram] using the Builder's accumulated string as argument.
//
// It returns an error if the provided metric is invalid, as per the [metrics.ValidateMetric] function.
//
// This is useful when you want to avoid the runtime panic generated by VM when a metric is invalid.
func (b *Builder) ValidateNewHistogramInSet(set *metrics.Set) (*metrics.Histogram, error) {
	name := b.String()
	if err := validateMetric(name); err != nil {
		return nil, err
	}
	return set.NewHistogram(name), nil
}
